CREATE TABLE worker (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    CONSTRAINT name_length_check
    CHECK (LENGTH(NAME) BETWEEN 2 AND 1000),
    BIRTHDAY DATE,
    CONSTRAINT birthday_year_check
    CHECK (YEAR(BIRTHDAY) > 1900),
    LEVEL VARCHAR NOT NULL,
    CONSTRAINT level_enum_values
    CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY BIGINT,
    CONSTRAINT salary_range_check
    CHECK (SALARY BETWEEN 100 AND 100000)
);

CREATE TABLE client (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    CONSTRAINT client_name_length_check
    CHECK (LENGTH(NAME) BETWEEN 2 AND 1000)
);

CREATE TABLE project (
    ID IDENTITY PRIMARY KEY,
    CLIENT_ID BIGINT NOT NULL,
    CONSTRAINT client_id_fk
    FOREIGN KEY (CLIENT_ID) REFERENCES client(ID),
    START_DATE DATE,
    FINISH_DATE DATE
);

CREATE TABLE project_worker (
    PROJECT_ID BIGINT NOT NULL,
    WORKER_ID BIGINT NOT NULL,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
);